spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 334521
    url: jdbc:mysql://localhost:3306/icytis_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC

#  jpa:
#    hibernate:
#      #     更新或者创建数据表结构
#      ddl-auto: update
#    #    控制台显示SQL
#    show-sql: true